BrutalBees/grace-shopper

- client/components/AuthForm.js
- client/components/Home.js
- client/components/ProductIndex.js
- client/components/ProductIndexItem.js
- client/store/auth.js
- client/store/index.js
- client/store/products.js
- server/auth/index.js
- server/db/models/User.js
- Added the ProductIndex and ProductIndexItem react components
- Changed AuthForm component to take in user email instead of username 
- Refactored store/auth.js to reflect changes
> feat: add ProductIndex and ProductIndexItem  component

- client/App.js
- client/Routes.js
- client/components/AuthForm.js
- client/components/Home.js
- client/components/Navbar.js
- client/components/ProductIndex.js
- client/components/ProductIndexItem.js
- client/store/auth.js
- public/index.css
- public/index.html
- script/seed.js
- server/api/users.js
- server/db/models/Product.js
home page styling and product model fix
> Home page styling 14

- client/components/Home.js
- client/components/Navbar.js
- public/index.css
Fixed the excess code from the previous merge
> fix: remove extra code from home-styling-page-14 merge

- client/App.js
- client/Routes.js
- client/components/AllProducts.js
- client/components/AuthForm.js
- client/components/Home.js
- client/components/Navbar.js
- client/components/ProductIndex.js
- client/components/ProductIndexItem.js
- client/components/styles.js
- client/store/auth.js
- script/seed.js
added a /products page to routes and styling
added navbar to app (will now render on every route)
removed history.push from me() thunk creator - so now every page doesn't redirect to home
moved styled-components to /components/styles.js
added seed files to test /products
> Products page styling 14

- public/index.css
- script/seed.js
- server/api/users.js
- server/auth/index.js
- server/auth/verifyToken.js
- server/db/models/User.js
api/users route now verifies admin access before sending back user information (first/last name, email)
refactored auth/me route to use the same middleware function to verify the token
> Refactor get users #54

- script/seed.js
- server/api/products.js
added POST /api/products route which allows admin users to add a new product
> Post products route #37

- client/Routes.js
- client/components/AdminProducts.js
- client/components/AdminView.js
- client/components/Navbar.js
- script/seed.js
- server/api/products.js
- server/db/models/Product.js
added Adminview and Adminproducts components that show the products an admin can edit on the /admin route
> Admin view component #34

- server/api/products.js
added PUT /api/product/:id route for admins to edit a product
> feat: put products route for admin use

- server/api/products.js
added DELETE api/products/:id for admin use
> Delete product route #35

- client/components/AdminProducts.js
- client/components/AdminView.js
- client/store/auth.js
- client/store/products.js
- client/store/singleProduct.js
closes #68 and #32 
connects the adminProducts view to backend routes
now admins can add, edit and delete products from database
completed styling
> Connect admin view to backend #68

- script/seed.js
- server/api/cart.js
fixed `GET api/cart` route to return cart associated with user and products
also creates cart for a user if they don't already have one
closes issue #22
> Story#4/get cart route/#22

- script/seed.js
- server/api/cart.js
- server/db/index.js
- allows users to add a specified quantity of a product to the cart
- closes #21
> feat: post cart route #21

- client/Routes.js
- client/components/Cart.js
- client/components/Navbar.js
- client/store/auth.js
- client/store/cart.js
- client/store/index.js
- script/seed.js
- server/api/cart.js
- server/db/index.js
- cart component connects to the cart reducer and renders products inside the cart
- added navbar link to cart
- added /cart route
- closes #39
> Story#4/cart component/#39

- client/Routes.js
- client/components/Cart.js
- client/components/Navbar.js
- client/store/auth.js
- client/store/cart.js
- client/store/index.js
- script/seed.js
- server/api/cart.js
- server/db/index.js
- created cart reducer
- cart reducer fetches the cart from /api/cart and sets it in the store
- closes #24
> Story#4/cart reducer/#24

- client/components/Cart.js
- client/components/CartProduct.js
- client/components/SignUp.js
- client/components/styles.js
- client/store/auth.js
- client/store/cart.js
completed styling cart component 
closes #60
> Story#4/style cart component/#60

- client/Routes.js
- client/components/Cart.js
- client/components/CartProduct.js
- client/components/OrderConfirmation.js
- client/store/cart.js
- server/api/cart.js
- server/auth/verifyToken.js
- completed `DELETE /api/cart/:productid` route to delete product
- updates reducer with new cart after product deleted
- added delete product button and handle delete to CartProduct component
- added OrderConfirmation component and linked to checkout button in cart
closes #80 #81 #82
> Story#5/cart component handle delete/#82

- client/Routes.js
- client/components/About.js
- client/components/Navbar.js
Finished Page... if time tonight I will add a "contact" section at the bottom
> feat:About page

- client/components/Cart.js
- client/components/SingleProduct.js
- client/components/styles.js
- client/store/cart.js
- server/api/cart.js
- server/db/index.js
- server/db/models/Cart.js
- adds isOrder column to cart model to differentiate between checked-out carts (orders) and current shopping carts
- changed association between user and cart to one to many
- closes #89 #90
> Story#6/checkout db and route/#89#90

- client/components/Cart.js
- client/components/Navbar.js
- client/components/styles.js
- client/store/cart.js
- checkout button on cart will change cart to order and fetches a new cart for the user
> feat: user can checkout cart #91 #92

- package.json
- script/seed.js
- server/db/models/Product.js
added fake user seeds and additional products
> feat: additional seed data

- client/components/About.js
- revert nodemon dependency to original version in boilerplate
- centered about text and changed image
> fix: nodemon dependency and about center text
